# NVIDIA NIM - Mistral-7B-Instruct v0.3
# TensorRT-LLM optimized inference with highest throughput
# Throughput: ~33.7 tok/s on NVIDIA A10
apiVersion: v1
kind: Service
metadata:
  name: mistral-nim-svc
  namespace: nim-bench
  labels:
    app: mistral-nim
    framework: nim
spec:
  selector:
    app: mistral-nim
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-nim
  namespace: nim-bench
  labels:
    app: mistral-nim
    framework: nim
    model: mistral-7b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mistral-nim
  template:
    metadata:
      labels:
        app: mistral-nim
        framework: nim
    spec:
      serviceAccountName: nim-bench-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /opt/nim/.cache && chmod -R 777 /opt/nim/.cache']
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
      containers:
      - name: nim
        image: nvcr.io/nim/mistralai/mistral-7b-instruct-v03:1.8.4
        env:
        - name: NIM_CACHE_PATH
          value: "/opt/nim/.cache"
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-secret
              key: NGC_API_KEY
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/gpu: "1"
          limits:
            memory: "64Gi"
            cpu: "16"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: nim-cache
          mountPath: /opt/nim/.cache
        - name: results
          mountPath: /results
        - name: tools
          mountPath: /tools
          readOnly: true
      volumes:
      - name: nim-cache
        hostPath:
          path: /mnt/coecommonfss/llmcore/2026-NIM-vLLM_LLM/nim-cache
          type: DirectoryOrCreate
      - name: results
        hostPath:
          path: /mnt/coecommonfss/llmcore/2026-NIM-vLLM_LLM/results/nim
          type: DirectoryOrCreate
      - name: tools
        hostPath:
          path: /mnt/coecommonfss/llmcore/2026-NIM-vLLM_LLM/tools
          type: Directory
      nodeName: 10.0.10.101  # GPU Node 2
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
